# Generated by Django 4.1.2 on 2022-11-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Long',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField(verbose_name=500)),
                ('custom_name', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
